[[redirects]]
  from = "/api/opencode_go/*"
  to = "/.netlify/functions/opencode/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/opencode_zen/*"
  to = "/.netlify/functions/opencode/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/openrouter/*"
  to = "https://openrouter.ai/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/openai/*"
  to = "https://api.openai.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/gemini/*"
  to = "https://generativelanguage.googleapis.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
